# Generated by Django 5.2.9 on 2025-12-04 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='保存場所名')),
            ],
            options={
                'verbose_name': '保存場所マスタ',
                'verbose_name_plural': '保存場所マスタ一覧',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食材名')),
                ('expiry_date', models.DateField(verbose_name='賞味期限/消費期限')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.location', verbose_name='保存場所ID')),
            ],
            options={
                'verbose_name': '食材管理',
                'verbose_name_plural': '食材管理一覧',
                'ordering': ['expiry_date'],
            },
        ),
    ]
