# Generated by Django 4.2.2 on 2025-12-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='食材カテゴリ名')),
            ],
            options={
                'verbose_name': '食材カテゴリマスタ',
                'verbose_name_plural': '食材カテゴリマスタ一覧',
            },
        ),
        migrations.CreateModel(
            name='FixedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='固定食材名')),
                ('default_quantity', models.PositiveIntegerField(default=1, verbose_name='デフォルト数量')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category', verbose_name='カテゴリ')),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location', verbose_name='デフォルト保存場所')),
            ],
            options={
                'verbose_name': '固定食材マスタ',
                'verbose_name_plural': '固定食材マスタ',
            },
        ),
    ]
