# Generated by Django 4.2.2 on 2025-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedingredient',
            name='is_quick_add',
            field=models.BooleanField(default=False, verbose_name='クイック追加対象'),
        ),
    ]
