# Generated by Django 4.2.2 on 2025-12-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_fixedingredient_is_quick_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='食材名')),
                ('category_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='食材カテゴリ')),
                ('quantity_used', models.PositiveIntegerField(verbose_name='使用数量')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='使用日時')),
                ('expiry_date_at_usage', models.DateField(blank=True, null=True, verbose_name='使用時の賞味期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '食材使用履歴',
                'verbose_name_plural': '食材使用履歴一覧',
                'ordering': ['-used_at'],
            },
        ),
    ]
