# Generated by Django 4.2.2 on 2025-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_usagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='購入店舗'),
        ),
    ]
