# Generated by Django 4.2.2 on 2025-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_ingredient_price_ingredient_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='price_at_usage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='購入時金額'),
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='store_name_at_usage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='購入店舗'),
        ),
    ]
