# Generated by Django 4.2.2 on 2025-12-10 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_usagehistory_price_at_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=100, unique=True, verbose_name='レシピID')),
                ('title', models.CharField(max_length=200, verbose_name='レシピ名')),
                ('url', models.URLField(verbose_name='レシピURL')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('cooking_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='調理時間')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('required_ingredients_text', models.TextField(help_text='カンマ区切りなどで必要な食材を保存', verbose_name='必要食材リスト')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
            },
        ),
    ]
